boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
IDT.o: IDT.c IDT.h lib.h types.h x86_desc.h keyboard.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  keyboard.h IDT.h
keyboard.o: keyboard.c keyboard.h i8259.h types.h lib.h
lib.o: lib.c lib.h types.h
