boot.o: boot.S multiboot.h x86_desc.h types.h
irq_handler.o: irq_handler.S
syscall_linkage.o: syscall_linkage.S ../syscalls/ece391sysnum.h \
  file_desc.h types.h syscall_linkage.h
x86_desc.o: x86_desc.S x86_desc.h types.h
file.o: file.c file.h types.h lib.h
file_desc.o: file_desc.c file_desc.h types.h file.h rtc.h i8259.h lib.h \
  keyboard.h
i8259.o: i8259.c i8259.h types.h lib.h
IDT.o: IDT.c IDT.h lib.h types.h x86_desc.h keyboard.h i8259.h rtc.h \
  syscall_linkage.h irq_handler.h systemCalls.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  keyboard.h IDT.h rtc.h Paging.h systemCalls.h file.h PIT.h
keyboard.o: keyboard.c keyboard.h i8259.h types.h lib.h systemCalls.h \
  Paging.h PCB.h file_desc.h
lib.o: lib.c lib.h types.h
Paging.o: Paging.c Paging.h types.h lib.h
PCB.o: PCB.c PCB.h types.h file_desc.h
PIT.o: PIT.c PIT.h lib.h types.h i8259.h
rtc.o: rtc.c rtc.h i8259.h types.h lib.h
Scheduler.o: Scheduler.c Scheduler.h types.h PCB.h file_desc.h lib.h \
  i8259.h keyboard.h x86_desc.h Paging.h
signal.o: signal.c
systemCalls.o: systemCalls.c systemCalls.h types.h file.h lib.h Paging.h \
  x86_desc.h keyboard.h i8259.h PCB.h file_desc.h
